version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_test
    volumes:
      - test-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  test:
    build:
      context: .
    command: bash -c "bundle exec rspec"
    volumes:
      - .:/app:cached
    depends_on:
      - db
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_test

volumes:
  test-db-data:
