require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admins", type: :request do
  let!(:school) { create(:school) }
  let!(:admin) { create(:admin, school: school) }
  
  let!(:term1) { create(:term, school: school) }
  let!(:term2) { create(:term, school: school) }

  let!(:course1) { create(:course, term: term1) }
  let!(:course2) { create(:course, term: term1) }

  let!(:student1) { create(:student, school: school) }
  let!(:student2) { create(:student, school: school) }
  # This should return the minimal set of attributes required to create a valid
  # Admin. As you add validations to Admin, be sure to
  # adjust the attributes here as well.
  describe "GET /show" do
    before do
      post school_admins_login_path(school), params: { email: admin.email, password: admin.password }

      create(:course_enrollment, course: course1, student: student1)
      create(:course_enrollment, course: course1, student: student2)
      create(:course_enrollment, course: course2, student: student1)

      create(:term_access, term: term1, student: student1, payment_method: "credit_card")
      create(:term_access, term: term1, student: student2, payment_method: "license")
      create(:term_access, term: term2, student: student2, payment_method: "license")
    end

    it "renders the dashboard successfully" do
      get school_admins_dashboard_path(school)
      expect(response).to have_http_status(:ok)
      expect(response.body).to include("Dashboard")
      expect(response.body).to include(course1.name)
      expect(response.body).to include(course2.name)
      expect(response.body).to include(term1.name)
      expect(response.body).to include(term2.name)
    end
  end
end
