require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/course_enrollments", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # CourseEnrollment. As you add validations to CourseEnrollment, be sure to
  # adjust the attributes here as well.

  let(:school) { create(:school) }
  let(:student) { create(:student, school: school) }
  let(:term) { create(:term, school: school) }
  let(:course) { create(:course, term: term) }

  before do
    post school_students_login_path(school), params: { email: student.email, password: student.password }
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_school_student_term_course_course_enrollment_path(school, student, term, course)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context 'when Course enrollment build success' do
      before do
        allow(CourseEnrollmentBuilder).to receive(:new).and_return(
          instance_double(CourseEnrollmentBuilder, call: true)
        )
      end

      it "redirect to student show page" do
        post school_student_term_course_course_enrollments_path(school, student, term, course)
        expect(response).to redirect_to(school_student_term_path(school, student, term))
      end
    end

    context 'when term access build failed' do
      before do
        allow(CourseEnrollmentBuilder).to receive(:new).and_return(
          instance_double(CourseEnrollmentBuilder, call: false)
        )
      end
      it "renders a new page" do
        post school_student_term_course_course_enrollments_path(school, student, term, course)
        expect(response).to render_template(:new)
      end
    end
  end

end
