require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/students", type: :request do
  let(:school) { create(:school) }
  let(:student) { create(:student, school: school) }
  let!(:term1) { create(:term, school: school) }
  let!(:term2) { create(:term, school: school) }

  describe "GET /schools/:school_id/students/:id" do
    context "when student is authenticated" do
      before do
        create(:term_access, student: student, term: term1)
        student.reload
        school.reload

        post school_students_login_path(school), params: { email: student.email, password: student.password }
        get school_student_path(school_id: school.id, id: student.id)
      end

      it "returns http success" do
        expect(response).to have_http_status(:success)
      end

      it "assigns accessible terms" do
        expect(assigns(:accessible_terms)).to include(term1)
      end

      it "assigns available terms" do
        expect(assigns(:available_terms)).to include(term2)
      end
    end

    context "when student is not authenticated" do
      it "redirects to login page" do
        get school_student_path(school_id: school.id, id: student.id)
        expect(response).to redirect_to(school_students_login_path)
      end
    end

    context "when accessing another student’s page" do
      let!(:other_student) do
        create(:student, school: school)
      end

      before do
        post school_students_login_path(school), params: { email: other_student.email, password: other_student.password }
      end

      it "redirect to root" do
        get school_student_path(school_id: school.id, id: student.id)
        expect(response).to redirect_to(root_path)
      end
    end
  end
end
