require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/terms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Term. As you add validations to Term, be sure to
  # adjust the attributes here as well.
  let(:school) { create(:school) }
  let(:student) { create(:student, school: school) }
  let(:term) { create(:term, school: school) }

  let!(:course_1) { create(:course, term: term) }
  let!(:course_2) { create(:course, term: term) }

  describe "GET /show" do
    before do 
      create(:term_access, student: student, term: term)
      create(:course_enrollment, student: student, course: course_1)
      student.reload
      school.reload
      term.reload

      post school_students_login_path(school), params: { email: student.email, password: student.password }
      get school_student_term_path(school, student, term)
    end

    it "returns http success" do
      expect(response).to have_http_status(:success)
    end

    it "assigns accessible terms" do
      expect(assigns(:accessible_courses)).to include(course_1)
    end

    it "assigns available terms" do
      expect(assigns(:available_courses)).to include(course_2)
    end
  end

end
