default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_test") %>
